---
- name: PostgreSQL | Configure | Directory Exists | {{ postgresql_runtime_root }}"
  become: yes
  file:
    state: directory
    path: "{{ postgresql_runtime_root }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    mode: 0765

- name: PostgreSQL | Configure | Ensure the locale is generated
  become: yes
  locale_gen: 
    name: "{{ postgresql_locale }}" 
    state: present

- name: PostgreSQL | Configure | environment
  become: yes
  template:
    src: "{{ postgresql_version }}/environment.j2"
    dest: "/etc/postgresql/{{ postgresql_version }}/main/environment"
    mode: 0644
    backup: yes
  notify: PostgreSQL | Handlers | Reload Service

- name: PostgreSQL | Configure | pg_ctl.conf
  become: yes
  template:
    src: "{{ postgresql_version }}/pg_ctl.conf.j2"
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_ctl.conf"
    mode: 0644
    backup: yes
  notify: PostgreSQL | Handlers | Reload Service

- name: PostgreSQL | Configure | pg_hba.conf
  become: yes
  template:
    src: "{{ postgresql_version }}/pg_hba.conf.j2"
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    mode: 0640
    backup: yes
  notify: PostgreSQL | Handlers | Reload Service

- name: PostgreSQL | Configure | pg_ident.conf
  become: yes
  template:
    src: "{{ postgresql_version }}/pg_ident.conf.j2"
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_ident.conf"
    mode: 0640
    backup: yes
  notify: PostgreSQL | Handlers | Reload Service

- name: PostgreSQL | Configure | postgresql.conf
  become: yes
  template:
    src: "{{ postgresql_version }}/postgresql.conf.j2"
    dest: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    mode: 0644
    backup: yes
  notify: PostgreSQL | Handlers | Reload Service

- name: PostgreSQL | Configure | start.conf
  become: yes
  template:
    src: "{{ postgresql_version }}/start.conf.j2"
    dest: "/etc/postgresql/{{ postgresql_version }}/main/start.conf"
    mode: 0644
    backup: yes
  notify: PostgreSQL | Handlers | Reload Service
