---
- name: PostgreSQL | Configure | Directory Exists | {{ postgresql_runtime_root }}"
  file:
    state: directory
    path: "{{ postgresql_runtime_root }}"
    owner: "{{ postgresql_user }}"
    group: staff
    mode: 0775

- name: PostgreSQL | Configure | Ensure the locale is generated
  become: yes
  locale_gen: name="{{ postgresql_locale }}" state=present

- name: PostgreSQL | Configure | pidfile
  lineinfile:
    state: present
    dest: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: '^#*external_pid_file'
    line: "external_pid_file = '{{ postgresql_pidfile_path }}'"
  notify: PostgreSQL | Handlers | Reload Service

- name: PostgreSQL | Configure | listen_address
  lineinfile:
    state: present
    dest: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: '^#* *listen_addresses ='
    line: "listen_addresses = '{{ postgresql_listen_addresses }}'"
  notify: PostgreSQL | Handlers | Reload Service
  when: postgresql_accepts_external_connections

- name: PostgreSQL | Configure | pg_hba.conf
  lineinfile:
    state: present
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    line: "host all all all md5"
  notify: PostgreSQL | Handlers | Reload Service
  when: postgresql_accepts_external_connections

- meta: flush_handlers
