---
- name: PostgreSQL | Users configuration | Ensure PostgreSQL is running
  service:
    name: "{{ postgresql_service_name }}"
    state: started

- name: PostgreSQL | Users configuration | Check Database User
  postgresql_user:
    name: "{{ item.name | default('dbuser') }}"
    password: "{{ item.password | default(omit) }}"
    db: "{{ item.db | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    expires: "{{ item.expires | default(omit) }}"
    fail_on_user: "{{ item.fail_on_user | default(omit) }}"
    login_host: "{{ item.login_host | default(omit) }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(omit) }}"
    login_user: "{{ item.login_user | default(omit) }}"
    no_password_changes: "{{ item.no_password_changes | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  when:  postgresql_server and (postgresql_users is defined)
  become_user: "{{ postgresql_user }}"
  with_items: "{{ postgresql_users }}"
  become_method: su
